# GitHub Actions Workflow for Feature Engineering Tests
#
# This workflow runs feature engineering tests against a CI Spark Connect cluster.
# Tests verify data availability, feature quality, and consistency.
#
# Triggers:
#   - Push to main branch (feature/** paths)
#   - Pull requests to main
#   - Scheduled daily at 6 AM UTC

name: Feature Engineering Tests

on:
  push:
    branches: [main]
    paths:
      - 'features/**'
      - 'tests/**'
      - '.github/workflows/feature-tests.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'features/**'
      - 'tests/**'
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test against'
        required: true
        default: 'ci'
        type: choice
        options:
          - ci
          - staging

env:
  PYTHON_VERSION: '3.11'
  SPARK_CONNECT_TEAM: feature-engineering
  SPARK_CONNECT_REGION: us-west-2

jobs:
  test-features:
    name: Test Feature Engineering
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyspark[connect] pytest pytest-xdist pandas

      - name: Set environment
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "SPARK_CONNECT_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          else
            echo "SPARK_CONNECT_ENV=ci" >> $GITHUB_ENV
          fi

      - name: Run data availability tests
        run: |
          pytest tests/feature_tests.py::TestDataAvailability -v --tb=short
        env:
          SPARK_CONNECT_TEAM: ${{ env.SPARK_CONNECT_TEAM }}
          SPARK_CONNECT_ENV: ${{ env.SPARK_CONNECT_ENV }}
          SPARK_CONNECT_REGION: ${{ env.SPARK_CONNECT_REGION }}

      - name: Run user feature tests
        run: |
          pytest tests/feature_tests.py::TestUserFeatures -v --tb=short
        env:
          SPARK_CONNECT_TEAM: ${{ env.SPARK_CONNECT_TEAM }}
          SPARK_CONNECT_ENV: ${{ env.SPARK_CONNECT_ENV }}
          SPARK_CONNECT_REGION: ${{ env.SPARK_CONNECT_REGION }}

      - name: Run item feature tests
        run: |
          pytest tests/feature_tests.py::TestItemFeatures -v --tb=short
        env:
          SPARK_CONNECT_TEAM: ${{ env.SPARK_CONNECT_TEAM }}
          SPARK_CONNECT_ENV: ${{ env.SPARK_CONNECT_ENV }}
          SPARK_CONNECT_REGION: ${{ env.SPARK_CONNECT_REGION }}

      - name: Run data quality tests
        run: |
          pytest tests/feature_tests.py::TestDataQuality -v --tb=short
        env:
          SPARK_CONNECT_TEAM: ${{ env.SPARK_CONNECT_TEAM }}
          SPARK_CONNECT_ENV: ${{ env.SPARK_CONNECT_ENV }}
          SPARK_CONNECT_REGION: ${{ env.SPARK_CONNECT_REGION }}

      - name: Generate test report
        if: always()
        run: |
          pytest tests/feature_tests.py -v --tb=short --junitxml=test-results.xml
        env:
          SPARK_CONNECT_TEAM: ${{ env.SPARK_CONNECT_TEAM }}
          SPARK_CONNECT_ENV: ${{ env.SPARK_CONNECT_ENV }}
          SPARK_CONNECT_REGION: ${{ env.SPARK_CONNECT_REGION }}
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results.xml

  notify-on-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: test-features
    if: failure() && github.event_name == 'schedule'

    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "Feature Engineering Tests Failed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚨 Feature Engineering Tests Failed"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Daily feature tests failed. Please investigate."
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow:*\n${{ github.workflow }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Details>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
